version: '3.8'
services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: familytree
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  backend:
    image: ghcr.io/magsimal/blauclan-backend:latest
    environment:
      DB_NAME: familytree
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      PORT: ${BACKEND_PORT:-3009}
    ports:
      - '${BACKEND_PORT:-3009}:${BACKEND_PORT:-3009}'
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
  frontend:
    image: ghcr.io/magsimal/blauclan-frontend:latest
    environment:
      BACKEND_PORT: ${BACKEND_PORT:-3009}
    ports:
      - '${FRONTEND_PORT:-8080}:80'
    depends_on:
      - backend
    restart: unless-stopped
volumes:
  db-data:
