version: '3'
services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: familytree
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    image: ghcr.io/magsimal/blauclan-backend:latest
    environment:
      DB_NAME: familytree
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      PORT: ${BACKEND_PORT:-3009}
    ports:
      - '${BACKEND_PORT:-3009}:${BACKEND_PORT:-3009}'
    depends_on:
      - db
  frontend:
    image: ghcr.io/magsimal/blauclan-frontend:latest
    environment:
      BACKEND_PORT: ${BACKEND_PORT:-3009}
    ports:
      - '8080:80'
    depends_on:
      - backend
volumes:
  db-data:
