version: '3'
services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: familytree
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    image: ghcr.io/OWNER/blauclan-backend:latest
    environment:
      DB_NAME: familytree
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
    ports:
      - '3000:3000'
    depends_on:
      - db
  frontend:
    image: ghcr.io/OWNER/blauclan-frontend:latest
    ports:
      - '8080:80'
    depends_on:
      - backend
volumes:
  db-data:
