name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_DB: familytree
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install backend deps
        run: |
          cd backend
          npm install
      - name: Run backend tests
        run: |
          cd backend
          npm test || true
      - name: Extract versions
        id: vars
        run: |
          BACKEND_VERSION=$(jq -r .version backend/package.json)
          echo "BACKEND_VERSION=$BACKEND_VERSION" >> "$GITHUB_OUTPUT"
          echo "FRONTEND_VERSION=0.1.0" >> "$GITHUB_OUTPUT"
      - name: Build Docker images
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/blauclan-backend:${{ steps.vars.outputs.BACKEND_VERSION }} \
            -t ghcr.io/${{ github.repository_owner }}/blauclan-backend:latest ./backend
          docker build -t ghcr.io/${{ github.repository_owner }}/blauclan-frontend:${{ steps.vars.outputs.FRONTEND_VERSION }} \
            -t ghcr.io/${{ github.repository_owner }}/blauclan-frontend:latest ./frontend
      - name: Push Docker images
        if: github.event_name == 'push'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker push ghcr.io/${{ github.repository_owner }}/blauclan-backend:${{ steps.vars.outputs.BACKEND_VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/blauclan-backend:latest
          docker push ghcr.io/${{ github.repository_owner }}/blauclan-frontend:${{ steps.vars.outputs.FRONTEND_VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/blauclan-frontend:latest
