name: Trigger Portainer Deploy via n8n

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  notify-n8n:
    if: ${{ github.event.workflow_run.conclusion == 'success' && (github.event.workflow_run.head_branch == 'main' || github.event.workflow_run.head_branch == 'develop') }}
    runs-on: ubuntu-latest
    container:
      image: curlimages/curl:latest

    steps:
      - name: Determine and Trigger
        env:
          WEBHOOK_URL: ${{ secrets.N8N_WEBHOOK_URL }}
          WEBHOOK_SECRET: ${{ secrets.N8N_WEBHOOK_SECRET }}
          REF: ${{ github.event.workflow_run.head_branch }}
        run: |
          if [[ "$REF" == "main" ]]; then
            STACK_ID=139
          elif [[ "$REF" == "develop" ]]; then
            STACK_ID=140
          else
            echo "No action for branch $REF"
            exit 0
          fi

          curl -X POST "$WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -H "x-n8n-secret: $WEBHOOK_SECRET" \
            -d "{\"stack_id\": $STACK_ID}"
